### ISSUE TITLE
how to get user id?

### ISSUE THREAD

**Issue by akshat9425** [oneilinteractive/SharpSpring-Client#2]
i am new to sharpspring please tell me how do i get user id

**Comment by dennisoneil** [comment]
Getting the lead id (assuming this is what you mean by "user id") is beyond the scope if this library -- which is designed for form submissions. However, you could extend it to handle this fairly easily.

Create this function:
```python
def get_leads(api, **where):
    api.method('getLeads')
    for k, v in where.items():
        api.where(k, v)
    leads = []
    resp = api.send()
    if resp.status_code == 200:
        data = resp.json()
        leads = data['result']['lead']
    return leads
```

And then call the function this way (where "api" is a SharpSpringRequest:
```python
try:
    leads = get_leads(api, emailAddress=email)
    lead = leads[0]
    lead_id = lead['id']
except Exception:
    raise SharpSpringAPIException(
        'The {} produced no leads from the SharpSpring API '
        .format(email))
```
Note that this code suggestion is not tested, and should be reviewed for your needs. YMMV.
