### ISSUE TITLE
Installing setup.py

### ISSUE THREAD

**Issue by 1001011era** [oneilinteractive/SharpSpring-Client#3]
I hope you realize how helpful and amazing this creation is here! Thank you! I am however having a hard-time installing setup.py. I was wondering if you could simply clarify the setup process? If time is allowed of course. If I click on the python file, a console flashes open and closes. I have tried running it from within a python console and even went as far as specifying the file directory for setup.py. I am going to continue fighting this battle but, I figured if it wouldn't hurt to through this out there for any others having issues. If I find the solution, I will update here to save you some finger work. :)

**Comment by dennisoneil** [comment]
Hello - This library is designed to be run as part of a web server/service. It's not going to be very useful if you're trying to run it through a file browsing GUI.

While there is no requirement that your entire app runs on Python, you will need some experience working with Python to use this library. A full walkthrough of this process is beyond what I'm able to support here. Best of luck with your project.

**Comment by 1001011era** [comment]
ok, Thank you.
